### ISSUE TITLE
Create tag for current version

### ISSUE THREAD

**Issue by petrdvorak** [fakturoid/fakturoid-php#12]
Please introduce basic versioning of the library. Nothing complicated is required, it just looks better to have the current working version tagged, instead of using the master branch...

**Comment by grogy** [comment]
Is possible create a tag for current version? We use it in Supportbox.cz and it looks fine.

Why create a tag? It is better for updating PHP dependencies, description is in [Composer documentation](https://getcomposer.org/doc/articles/versions.md#tags)

Thanks for your time. If you want help with it you can write me :)

**Comment by ollie** [comment]
Yes we'll look into it. Hopefully sooner than later. 😃

**Comment by ollie** [comment]
I just tagged the current version. 🎉

**Comment by grogy** [comment]
Great, thank you! We at SupportBox.cz try it in this week :smiley:
