### ISSUE TITLE
Searching for Invoice's tags with query specified returns unfiltered results

### ISSUE THREAD

**Issue by marecektn** [fakturoid/fakturoid-php#14]
I am trying to search for Invoices with specified filtered parameter (I am curious about `tag` parameter)

This is how my search call for subjects looks like:
```
$tag = 'zzz-www-333';
$invoices = $fakturoid->search_invoices(array('query' => $tag));
```

The issue is, that first 20 invoices is returned, but these are no filtered according to search query.
I do have invoice with that tag in the system already (I do know by fetching unfiltered invoices and filtering manually)

Thanks for help 💪

**Comment by marecektn** [comment]
when using search query for Subject name, searching works just fine.. the problem is with `tags` only

**Comment by ollie** [comment]
Hello, I'm trying to reproduce this locally and I'm not having much luck. Could you please try your script again and then send us an email to podpora@fakturoid.cz with your account slug (you don't have to use english there)? That way I can pull it out from logs easily and start debugging.

Thanks!
