### ISSUE TITLE
Headers lower/upper case mismatch

### ISSUE THREAD

**Issue by medhi** [fakturoid/fakturoid-php#18]
We are webhosting company and our client uses this library on our hosting. Our configuration returns names of these headers on lower-case, like this:

`'content-type' => 'application/json; charset=utf-8'`

But this library expects first letters uppercase, so it doesn't match, therefore, it doesn't work.

https://github.com/fakturoid/fakturoid-php/blob/3f424187ddbef8eb12e6a88e36503a72de0c6e94/lib/Fakturoid/Response.php#L52

**Comment by ollie** [comment]
Hello, thank you for reporting, could you please try new version?
