### ISSUE TITLE
Úprava odběratele?

### ISSUE THREAD

**Issue by theodovgopol** [fakturoid/fakturoid-php#22]
Zdravím,
je možné přes API upravit odběratele na údaje faktuře(jméno, příjmení, atd...)? Když zavolám `$this->fakturoidApi->updateSubject("subject_id", ["data"]);`
Tak se kontakt sice v `app.fakturoid.cz/foo/subjects` změní, ale na faktuře stejně zůstanou staré údaje.

**Comment by edariedl** [comment]
Dobrý den,
změny kontaktů se do již vystavených faktur nepřenáší, aplikují se až na nově vystavené faktury.

Upravit údaje odběratele na faktuře lze přes API pouze v placených tarifech a to přes `updateInvoice($id, $data)`, kde nastavíte `client_*` attributy viz [API dokumentace](https://fakturoid.docs.apiary.io/#reference/invoices).

Pokud máte tarif Zdarma, změna přes API udělat nelze.
