### ISSUE TITLE
Protected přístup k metodám

### ISSUE THREAD

**Issue by TakeruDavis** [fakturoid/fakturoid-php#25]
Bylo by prosím možné změnit přístup k metodám get/post/patch/delete/filterOptions na protected?

Chápu, že jsou tyto metody myšlené jako interní. 
V klientovi ale chybí přístup k některým API endpointům (prozatím vím pouze o jednom - GET https://app.fakturoid.cz/api/v2/accounts/slug/bank_accounts.json, ale nevím jestli v průbehu vývoje ještě na nějaké nenarazím)

Momentálně řeším vykopírováním zmíněných metod do rozšiřující třídy, ale obvykle duplikaci kódu nepovažuji za nejvhodnější řešení

**Comment by edariedl** [comment]
Díky za upozornění. Z naší strany dává větší smysl implementovat chybějící endpointy přímo do klienta. Chcete poslat pull request? Případně je můžeme naimplementovat přímo my.

**Comment by TakeruDavis** [comment]
Jo, pull request poslat mohu, akorát než najdu případné chybějící endpointy, tak to chvíli potrvá, vývoj teď není prioritní. Kdyžtak bych to rozdělil do více PR, začínajíc s bank_account
