### ISSUE TITLE
Nepochopitelný HTTP CODE 500

### ISSUE THREAD

**Issue by Javorxdd** [fakturoid/fakturoid-php#30]
Zdravím, 

po vytvoření faktury jakožto: pay_proforma dostávám nepochopitelný kód 500, ikdyž je faktura vytvořená a přijde mi do mailu.
Chyba:  [error] 26#26: *1764 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Fakturoid\Exception: {"errors":{"event":"pay_proforma cannot be fired"}}

**Comment by edariedl** [comment]
@Javorxdd Dobrý den, odpověď `422 Unprocessable entity` s tuto chybouvou hláškou API typicky vrací, když není možné danou akci vykonat nad daným dokladem, například protože je zálohovka už zaplacená, nebo se nejedná o zálohovku.

Pošlete prosím detaily na podpora@fakturoid.cz - zejména o jaký konkrétní účet a doklad se jednalo - na základě těchto infomrací by mělo být možné zjistit, pro API vrátilo právě tuto odpověď.

**Comment by Javorxdd** [comment]
@edariedl 
Dobrý den,

poprosím Vás, aby jste si znovu přečetl nadpis a text toho vlákna. Tímto se tak vyhneme možné budoucí hádce. Nic o 422 Unprocessable entity nevím.

**Comment by edariedl** [comment]
@Javorxdd Dobrý den,

omlouvám se za nedostatečné vysvětlení.

Před odpovědí jsem prověřoval logy i zdrojové kódy Fakturoidu. Logy neukazovaly žádný status kód 500 Internal serve error při volání `invoices/id/fire.json?event=pay_proforma`.  Stejně tak podle zdrojových kódů Fakturoid neumí vrátit tělo odpovědi `{"errors":{"event":"pay_proforma cannot be fired"}}` a zároveň status kód 500 Internal server error. S touto chybou se vždy vrací status kód 422 Unprocessable entity. Neevidujeme ani žádné produkční výjimky z volání `pay_proforma`.

PHP knihovna [vyhodí výjimku](https://github.com/fakturoid/fakturoid-php#handling-errors) `Fakturoid\Exception` vždy když se z API vrátí status kód 400 a vyšší. Proto jsem předpokládal, že šlo u status kódu spíš o přehlédnutí. Za to se omlouvám.

Pro důkladnější prověření opravdu potřebujeme, abyste nám napsal na podpora@fakturoid.cz s detaily o jaký doklad se jednalo a kdy přesně se požadavek posílal. Bez toho není možné prověřit co přesně se stalo.

**Comment by Javorxdd** [comment]
Již jsem posílal error paní do chatu, když jsem s ní něco řešil. Tato chyba se mi ukázala vždy, když jsem vytvářel fakturu ve stylu: „pay_proforma.“

**Comment by Javorxdd** [comment]
A bude ta faktura při použití atributu „pay“ vytvořená jako zaplacená, nebo ne?

**Comment by edariedl** [comment]
Vytvoření a zaplacení faktury jsou vždy 2 API požadavky:

1. Vytvoříte fakturu přes POST `/api/v3/accounts/{slug}/invoices.json`
2. Nově vytvořenou fakturu zaplatíte přes `/api/v3/accounts/{slug}/invoices/{id}/fire.json?event=pay`

**Comment by Javorxdd** [comment]
Já bych ji právě potřeboval vytvořit. Zaplacenou posílám jinak.

**Comment by edariedl** [comment]
S tím prosím napište na podpora@fakturoid.cz a popište, čeho se snažíte dosáhnout a přidat i kontext proč ať Vám můžeme poradit přímo pro Vaši konkrétní situaci.
