### ISSUE TITLE
OAuth token refresh

### ISSUE THREAD

**Issue by Papajik** [fakturoid/fakturoid-php#34]
Dobrý den, 
ve funkci  [_oauth2refresh_](https://github.com/fakturoid/fakturoid-php/blob/582cbe7f538bb37c4d1354dc3c20283e116143d3/src/Auth/AuthProvider.php#L114C24-L118C24) je do body přidáno client_id a client_secret, což podle všeho způsobuje nemožnost získání nového tokenu:

```
{
    "error": "invalid_request",
    "error_description": "Client ID and Client Secret have to be sent via HTTP Basic Authorization"
}
```

Můžete to prosím prověřit?

**Comment by Papajik** [comment]
Zároveň je chyba při vzniku [nového Credentials objektu](https://github.com/fakturoid/fakturoid-php/blob/582cbe7f538bb37c4d1354dc3c20283e116143d3/src/Auth/AuthProvider.php#L138C13-L138C48)

JSON odpovědi obsahuje access_token, token_type a expires_in. Refresh token je tedy v novém Credentials objektu null, což při dalším dotazu vyústí v **AuthorizationFailedException** Invalid credentials. Nebylo by lepší do fallbacku dát předchozí validní refresh token?

`$json['refresh_token'] ?? $this->credentials->getRefreshToken()`

**Comment by Papajik** [comment]
Dobrý den, 
první část se projeví hned, pokud postupuji podle příkladu pro code flow:

  ```
// Nejprve vytvořím instanci managera pro aplikaci
   
  $manager = new FakturoidManager(
          client: new Client(),
          clientId: 'client_id',
          clientSecret: 'client_secret',
          userAgent: 'user_agent',
          accountSlug: null,
          redirectUri: 'redirect_uri',
      );
        
// Přidám access a refresh token, který jsem dostal od druhého uživatele poté, co autorizoval přístup z aplikace

  $credentials = new Credentials(
      refreshToken: 'refresh_token',
      accessToken: 'access_token',
      expireAt: (new \DateTimeImmutable())->modify('-2 minutes'),
      authType: AuthTypeEnum::AUTHORIZATION_CODE_FLOW
  );
  
  $manager->setCredentials($credentials);
  $manager->setAccountSlug('--slug--');
  
  $manager->getUsersProvider()->getCurrentUser(); // <-- Tady dostanu AuthorizationFailedException

```

V knihovně vidím, že se posílá v těle json v tomto tvaru:

```
{
  "grant_type": "refresh_token",
  "refresh_token": "--refresh_token--",
  "redirect_uri":"--redirect_uri--",
  "client_id":"--client_id--",
  "client_secret":"--client_secret--"
}
```

Odpověď:

```
{
    "error": "invalid_request",
    "error_description": "Client ID and Client Secret have to be sent via HTTP Basic Authorization"
}
```

V knihovně odstraním [tyto řádky ](https://github.com/fakturoid/fakturoid-php/blob/582cbe7f538bb37c4d1354dc3c20283e116143d3/src/Auth/AuthProvider.php#L115-L116), chyba zmizí a dostanu data o uživateli

**Comment by tomas-kulhanek** [comment]
@Papajik díky moc! Mrknu na to a chybu opravím během dneška.

**Comment by Papajik** [comment]
Děkuji za rychlou reakci

Druhá chyba chyba má stejné flow, jen zduplikuji poslední volání:
 
```
$manager = new FakturoidManager(
        client: new Client(),
        clientId: 'client_id',
        clientSecret: 'client_secret',
        userAgent: 'user_agent',
        accountSlug: null,
        redirectUri: 'redirect_uri',
    );
      
$credentials = new Credentials(
    refreshToken: 'refresh_token',
    accessToken: 'access_token',
    expireAt: (new \DateTimeImmutable())->modify('-2 minutes'),
    authType: AuthTypeEnum::AUTHORIZATION_CODE_FLOW
);

$manager->setCredentials($credentials);
$manager->setAccountSlug('--slug--');

$manager->getUsersProvider()->getCurrentUser();
$manager->getUsersProvider()->getCurrentUser();  <-- Tady dostanu AuthorizationFailedException (Invalid credentials)
```

Refresh token byl totiž při první obnovení [vymazán](https://github.com/fakturoid/fakturoid-php/blob/582cbe7f538bb37c4d1354dc3c20283e116143d3/src/Auth/AuthProvider.php#L138)

**Comment by tomas-kulhanek** [comment]
@Papajik v branchi `34-oauth-token-refresh` by to mělo být opraveno. v #35  je i Váš sample, na kterém jsem to zkoušel
